spring:
  application:
    name: matching-engine
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    instance:
      preferIpAddress: true
    healthcheck:
      enabled: true
server:
  port: 9002