server:
  port: 9001

eureka:
  instance:
    health-check-url: https://${eureka.hostname}/actuator/health
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/