spring:
  application:
    name: conciliator

eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    healthcheck:
      enabled: true

server:
  port: 9005

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

slack.notification:
  server: https://hooks.slack.com/services/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

influx:
  db:
    host: http://127.0.0.1:8086
    username: root
    password: root
    database: tianguix
